export const SET_CITY_FORECAST_DATA = 'SET_CITY_FORECAST_DATA';
export const SET_CITY_FORECAST_IS_LOADING = 'SET_CITY_FORECAST_IS_LOADING';
export const SET_CITY_FORECAST_IS_ERROR = 'SET_CITY_FORECAST_IS_ERROR';

export const API_KEY = `73a790aa2cc4440e897ba2ba13842a4f`;